"""add_illness_and_product_tables

Revision ID: e58d32521b06
Revises: 
Create Date: 2026-05-27 12:00:44.748276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e58d32521b06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_products_user_id'), 'products', ['user_id'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_user_id'), table_name='products')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
